#sub_path_only rewrite ^__PATH__$ __PATH__/ permanent;
location __PATH__/ {

  proxy_pass http://127.0.0.1:__PORT__;

  include proxy_params_no_auth;
  include proxy_params_no_auth;
  # include conf.d/yunohost_panel.conf.inc;
}

location = / {
  if ($is_args = "") {
    return 301 /js/embed.min.js;
  }
  proxy_pass http://127.0.0.1:__PORT__;
  include proxy_params_no_auth;
}