#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

email=$(ynh_user_get_info --username=$admin --key=mail)
ynh_app_setting_set --key=password --value=$password

#=================================================
# Setup Final Path
#=================================================
ynh_script_progression "Setting up source files..."

mkdir -p $install_dir

#REMOVEME? Assuming the install dir is setup using ynh_setup_source, the proper chmod/chowns are now already applied and it shouldn't be necessary to tweak perms | chmod -R o-rwx "$install_dir"
#REMOVEME? Assuming the install dir is setup using ynh_setup_source, the proper chmod/chowns are now already applied and it shouldn't be necessary to tweak perms | chown -R $app:www-data "$install_dir"
#=================================================
# NGINX CONFIGURATION
#=================================================
ynh_script_progression "Configuring NGINX web server..."

# Create a dedicated NGINX config
ynh_config_add_nginx

#=================================================
# SPECIFIC SETUP
#=================================================

pushd $install_dir
	ynh_exec_as_app python3 -m venv $install_dir/venv
	ynh_exec_as_app "$install_dir/venv/bin/pip" install --upgrade pip
	ynh_exec_as_app "$install_dir/venv/bin/pip" install --upgrade setuptools
	ynh_exec_as_app "$install_dir/venv/bin/pip" install --upgrade MarkupSafe
	ynh_exec_as_app "$install_dir/venv/bin/pip" install isso gunicorn
popd

#=================================================
# ADD A CONFIGURATION
#=================================================
ynh_script_progression "Adding $app's configuration..."

ynh_config_add --template="isso.cfg" --destination="$install_dir/isso.cfg"

chmod 400 "$install_dir/isso.cfg"
chown $app:$app "$install_dir/isso.cfg"

#=================================================
# SETUP SYSTEMD
#=================================================
ynh_script_progression "Configuring $app's systemd service..."

# Create a dedicated systemd config
ynh_config_add_systemd

# Use logrotate to manage application logfile(s)
ynh_config_add_logrotate

yunohost service add $app --description="Lightweight commenting server" --log="/var/log/$app/$app.log"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

# Start a systemd service
ynh_systemctl --service=$app --action="start" --log_path="systemd"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
