#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

email=$(ynh_user_get_info --username=$admin --key=mail)
ynh_app_setting_set --key=password --value=$password

#=================================================
# Setup Final Path
#=================================================
ynh_script_progression "Setting up source files..."

mkdir -p $install_dir

chmod -R o-rwx "$install_dir"
chown -R $app:www-data "$install_dir"

#=================================================
# SPECIFIC SETUP
#=================================================

pushd $install_dir
	ynh_exec_as_app python3 -m venv $install_dir/venv
	ynh_exec_as_app "$install_dir/venv/bin/pip" install --upgrade pip
	ynh_exec_as_app "$install_dir/venv/bin/pip" install --upgrade setuptools
	ynh_exec_as_app "$install_dir/venv/bin/pip" install --upgrade MarkupSafe
	ynh_exec_as_app "$install_dir/venv/bin/pip" install isso gunicorn
popd

#=================================================
# ADD A CONFIGURATION
#=================================================
ynh_script_progression "Adding $app's configuration..."

ynh_config_add --template="isso.cfg" --destination="$install_dir/isso.cfg"

#=================================================
# SETUP SYSTEMD
#=================================================
ynh_script_progression "Configuring $app's systemd service..."

ynh_config_add_nginx

ynh_config_add_systemd

ynh_config_add_logrotate

yunohost service add $app --description="Lightweight commenting server" --log="/var/log/$app/$app.log"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service=$app --action="start" --log_path="systemd"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
